### ISSUE TITLE
React 17 - Webpack fallback error

### ISSUE THREAD

**Issue by Flo0806** [junkurihara/jscu#1064]
Hello!
I have installed your library per npm. I import it with 'import rsa from "js-crypto-rsa"' (in my case i have only installed the rsa part). If i start my react app with npm start the follow error appear: 
`
If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
`
Can you help?

Greatings, Flo

**Comment by junkurihara** [comment]
Hi Florian,

Although I am not familiar with React, I believe it can be solved add following in your `webpack.config.js`.

```javascript:webpack.config.js
{
  resolve:
   {
     fallback: { 'crypto': false }
   }
 }
```

This is due to the recent change of Webpack's bundling policy of polyfills. For `js-crypto-rsa`, you don't need to install `crypto-browserify` in your project. It simply kicks the native cryptographic APIs of browsers. You can also see an example in my another repo: https://github.com/junkurihara/generate-password/blob/develop/webpack.config.js#L17-L23

Cheers,
Jun

**Comment by junkurihara** [comment]
Ah, if you use `create-react-app` and don't want to `eject`, this may help you: https://github.com/timarney/react-app-rewired
This overrides `create-react-app`'s webpack config. So you could add the `resolve.fallback....` in `config-overrides.js`.
