### ISSUE TITLE
clarify readme.md

### ISSUE THREAD

**Issue by abhijithvijayan** [junkurihara/jscu#120]
https://github.com/junkurihara/jscu/blob/develop/packages/js-crypto-hkdf/README.md#derive-key-from-a-master-secret-without-salt-salt-is-randomly-generated-inside-the-function

The headings are misplaced. First set of code corresponds to one without salt and second corresponds to one with salt.
 
also isn't it `hkdf.compute.....` instead of `hmac.compute...`

```
hmac.compute(masterSecret, hash, length, info, salt).then( (derivedKey) => {
  // now you get a key derived from the masterSecret
});
```

**Comment by abhijithvijayan** [comment]
Also is this the expected output for some 16 bytes salt

![Screenshot from 2019-06-21 15-58-40](https://user-images.githubusercontent.com/34790378/59916781-bd382500-943d-11e9-84fc-a6e488d8d38d.png)

**Comment by junkurihara** [comment]
@abhijithvijayan thanks for your comment. I just fixed the README.md in the repo of `js-crypto-hkdf`.

**Comment by abhijithvijayan** [comment]
@junkurihara Thanks for clarifying, could you also confirm if the output I get was indeed the right one(or at least that's how its gonna look like)?

**Comment by junkurihara** [comment]
@abhijithvijayan ah ok. the function `compute` actually outputs the object in the form `{key: uint8array, salt: uint8array}`. The salt value would be filled when you don't explicitly input the salt into the function, otherwise it just returns as is. also please put your salt in uint8array.

you can encode the string salt to uint8array using my `js-encoding-utils` like
```
import jseu from 'js-encoding-utils'
const stringSalt = 'abc@gmail.com';
const uint8Salt = jseu.encoder.stringToArrayBuffer(stringSalt);
```
