### ISSUE TITLE
Uint8Array key to JWK Object

### ISSUE THREAD

**Issue by abhijithvijayan** [junkurihara/jscu#121]
Can [js-crypto-key-utils](https://github.com/junkurihara/jscu/tree/develop/packages/js-crypto-key-utils) be used to set a **Uint8Array** with the structure of a **jwk** object

Something like this
```
Uint8Array(32) [217, 75, 191, 175, 56, 204, 195, 184, 100, 8, 111, 246, 165, 76, 251, 227, 86, 250, 37, 57, 35, 62, 191, 131, 221, 73, 44, 115, 107, 105, 153, 240]
```
to
```
KCVXrFs8oJBheco-JxbHkPL9bxyN5\WZ68hyfVgrBuJg
```

**Comment by junkurihara** [comment]
@abhijithvijayan Do you mean a symmetric key (i.e., just a random binary sequence) in jwk format? if so, no. `js-crypto-key-utils` was not designed to support a JWK format of symmetric keys since other formats like DER/PEM doesn't support symmetric keys (as far as I know).

However, the symmetric key in jwk format is quite simple as indicated in rfc7517 (https://tools.ietf.org/html/rfc7517). For instance, an 128 bit key with an explicit algorithm is like
```
{ "kty":"oct",
  "alg":"A128KW",
  "k":"GawgguFyGrWKav7AX4VKUg" },
```
and some HMAC key is like
```
{ "kty":"oct",
  "k":"AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75
     aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow",
  "kid": "HMAC key used in JWS spec Appendix A.1 example" }
```
Anyways, you can obtain a jwk of a symmetric key by encoding its uint8array form to base64url form and putting it as "k" as above.

**Comment by abhijithvijayan** [comment]
@junkurihara Thanks for clarifying.

As you said, I encoded the key to base64url and created a jwk.
