### ISSUE TITLE
cannot encrypt more than 190 bytes

### ISSUE THREAD

**Issue by bebeljs** [junkurihara/jscu#566]
const rsa = require('js-crypto-rsa')

const msg = Uint8Array.from([
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
])

rsa.generateKey(2048).then(key => {
  const publicKey = key.publicKey
  const privateKey = key.privateKey

  rsa.encrypt(msg, publicKey, 'SHA-256', {name: 'RSA-PSS'})
    .then(encrypted => {
      console.log(encrypted)
      return rsa.decrypt(encrypted, privateKey, 'SHA-256', {name: 'RSA-PSS'})
    })
    .then(decrypted => {
      console.log(decrypted)
    })
})

=>

(node:12827) UnhandledPromiseRejectionWarning: Error: MessageTooLong

**Comment by junkurihara** [comment]
Hey @babeljs,

You have two misunderstanding. First, RSA-PSS is a signature scheme. (The error-message might be wrong though.) You should try RSA-OAEP or RSASSA-PKCS1. 

Secondly, if you employ an RSA encryption, the maximum size of message is limited by the public key size, which is theoretically well-known. For example, plaintext of at most 2048bits (=256bytes) can be encrypted by vanilla RSA. So, if you want to encrypt a long message, you should use AES to encrypt the message and use RSA to encrypt the AES key.

**Comment by bebeljs** [comment]
Thanks for your answer. Two questions :

1) What are dp, dq, and qi in privateKey ? How can I calculate them from n, e and p and q ?

2) Starting from this sequence :
encrypted = rsa.encrypt(msg, publicKey)
msg = rsa.decrypt(encrypted, privateKey)

why it's not possible to encrypt and decrypt with encrypt method as :
encrypted = rsa.encrypt(msg, publicKey)
newKey = {
kty: 'RSA',
n: publicKey.n
e: privateKey.d
}
msg = rsa.encrypt(encrypted, specialPrivateKey)

**Comment by junkurihara** [comment]
Hey @bebeljs,

For the first question,  they are used for simpler representation, and also required in JWK format for RSA private keys. Yes they can be obtained from e, p and q. For the detailed explanation, you should google it or read the JWK spec.

For the second question, I don't catch your question there... What do you mean? Is it a question about key format?

**Comment by bebeljs** [comment]
I am writing a npm module which allows to regenerate the user's private key from his password. 
This is a project to create a distributed authentication system based on RSA. My problem is that I cannot use your module because the private key requires values ​​that I cannot calculate (dp, dq, qi). If these values ​​are not entered the library crashes. Do you have a solution for me?

**Comment by bebeljs** [comment]
d

**Comment by junkurihara** [comment]
Hey @bebeljs 

>  My problem is that I cannot use your module because the private key requires values ​​that I cannot calculate (dp, dq, qi).
OK I see. I believe dp, dq, and qi, are **SHOULD BE PRESENTED** values in the specification of JSON Web Key (JWK) (See https://tools.ietf.org/html/rfc7518#section-6.3.2 ). Note that only d is a "MUST BE PRESENTED" value, which implies it may work without dp, dq, qi in some environment. However, they are "Required JWK members" (i.e., mandatory) at least in WebCrypto API of Chrome, and hence they are required to be set. Since my library fully utilize the underlying native engines like WebCryptoAPI, they are required values as well. (Thus, as you see, this is not the limitation of my library.)

One possible solution is to calculate these values from p, q, and d by yourself, which is not actually tough task. You can derive them by referring to some websites like: https://crypto.stackexchange.com/questions/19413/what-are-dp-and-dq-in-encryption-by-rsa-in-c

Another solution may be to use private keys in other format like PEM/DER (if you have), and covert them to JWK via my another library 'js-crypto-key-utils'.

**Comment by bebeljs** [comment]
I unterstand. Another solution consists to consider that the true key is the JWK required in WebCrypto API and not just, p or d, and that solve my problem.
I imagine your library does not calculate the p, q, d... values directly but relies on the API to do it ?
Thanks for your help.
